name: "CI"

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Secret Dection
        uses: zricethezav/gitleaks-action@master
        with:
          config-path: .gitleaks.toml

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    name: Build
    runs-on: ubuntu-18.04
    needs: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Hadolint
        uses: brpaz/hadolint-action@v1.3.1
        with:
          dockerfile: Dockerfile

      - name: Build Dockerfile
        run: |
          docker build -t docker.io/lpmatos/hrpurge/hrpurge:${{ github.sha }} .

      - name: Dive
        uses: yuichielectric/dive-action@0.0.4
        with:
          image: "docker.io/lpmatos/hrpurge/hrpurge:${{ github.sha }}"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Trivy Vulnerability Scanner
        id: trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "docker.io/lpmatos/hrpurge/hrpurge:${{ github.sha }}"
          format: "template"
          template: "@/contrib/sarif.tpl"
          output: "trivy-results.sarif"

      - name: Upload Trivy Scan Results to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: "trivy-results.sarif"

      - name: Send Success Custom Message to Telegram
        if: ${{ success() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🤖 Github action notify 🤖

            ✅ Sucess ${{ github.event_name }} event triggered:

            - Git Ref: ${{ github.ref }}
            - Git Commit Hash: ${{ github.sha }}
            - Commit Message: ${{ github.event.head_commit.message }}

      - name: Send Failure Custom Message to Telegram
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🤖 Github action notify 🤖

            ❌ Failure ${{ github.event_name }} event triggered:

            - Git Ref: ${{ github.ref }}
            - Git Commit Hash: ${{ github.sha }}
            - Commit Message: ${{ github.event.head_commit.message }}
