name: "CI"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  gitleaks:
    name: Secret Detection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run gitleaks secrets scan action
        uses: zricethezav/gitleaks-action@master
        with:
          config-path: .gitleaks.toml

  dive:
    runs-on: ubuntu-latest
    name: Analyze image efficiency
    needs: gitleaks
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build image
        run: docker build -t sample:latest .

      - name: Dive
        uses: yuichielectric/dive-action@0.0.4
        with:
          image: "sample:latest"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Hadolint
        uses: brpaz/hadolint-action@v1.2.1
        with:
          dockerfile: Dockerfile

  build:
    name: Build
    runs-on: ubuntu-18.04
    needs: dive
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/lpmatos/hrpurge/hrpurge:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "docker.io/lpmatos/hrpurge/hrpurge:${{ github.sha }}"
          format: "template"
          template: "@/contrib/sarif.tpl"
          output: "trivy-results.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: "trivy-results.sarif"
