name: "CI"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dive:
    runs-on: ubuntu-latest
    name: Analyze image efficiency
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        run: docker build -t sample:latest .
      - name: Dive
        uses: yuichielectric/dive-action@0.0.4
        with:
          image: "sample:latest"
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Hadolint
        uses: brpaz/hadolint-action@v1.2.1
        with:
          dockerfile: Dockerfile

  build:
    name: Build
    runs-on: ubuntu-18.04
    needs: dive
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/lpmatos/hrpurge/hrpurge:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "docker.io/lpmatos/hrpurge/hrpurge:${{ github.sha }}"
          format: "template"
          template: "@/contrib/sarif.tpl"
          output: "trivy-results.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: "trivy-results.sarif"
