name: "CI"

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  gitleaks:
    name: Secret Detection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run gitleaks secrets scan action
        uses: zricethezav/gitleaks-action@master
        with:
          config-path: .gitleaks.toml

  sonarcloud:
    name: Sonar Cloud
    runs-on: ubuntu-latest
    needs: gitleaks
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  dive:
    runs-on: ubuntu-latest
    name: Analyze image efficiency
    needs: [gitleaks, sonarcloud]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build image
        run: docker build -t sample:latest .

      - name: Dive
        uses: yuichielectric/dive-action@0.0.4
        with:
          image: "sample:latest"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Hadolint
        uses: brpaz/hadolint-action@v1.3.1
        with:
          dockerfile: Dockerfile

  build:
    name: Build
    runs-on: ubuntu-18.04
    needs: dive
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/lpmatos/hrpurge/hrpurge:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "docker.io/lpmatos/hrpurge/hrpurge:${{ github.sha }}"
          format: "template"
          template: "@/contrib/sarif.tpl"
          output: "trivy-results.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: "trivy-results.sarif"

      - name: send custom message with args
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            The ${{ github.event_name }} event triggered second step.
            show the github variable ref: ${{ github.ref }}
            show the github variable commit: ${{ github.sha }}
            show the github variable ref: {{ commit.ref }}
            show the github variable commit: {{ commit.sha }}
            Commit Message: ${{ github.event.head_commit.message }}
